## 0520    

### 查漏补缺

关于 `Promise.prototype.then` 提供的参数不是函数，那就当没提供这个 handler，也不会报错，同时之前的 promise 状态会向后传递。    

```ts
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)
```   

最后打印了 1.    

- `.finally()`方法的回调函数不接受任何的参数，也就是说你在.finally()函数中是无法知道Promise最终的状态是resolved还是rejected的   
- 它最终返回的默认会是一个上一次的Promise对象值，不过如果抛出的是一个异常则返回异常的Promise对象。   

